import QtQuick 2.0
import QtQuick.Controls 2.0

Item {
    width : 480
    height: 360

    ListModel {
        id: objects
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
        ListElement { mainColor :"#00FF00" ; secondColor: "#FF00FF" }
        ListElement { mainColor :"#00EE00" ; secondColor: "#FF11FF" }
        ListElement { mainColor :"#00DD00" ; secondColor: "#FF22FF" }
        ListElement { mainColor :"#00CC00" ; secondColor: "#FF33FF" }
        ListElement { mainColor :"#00BB00" ; secondColor: "#FF44FF" }
        ListElement { mainColor :"#00AA00" ; secondColor: "#FF55FF" }
        ListElement { mainColor :"#009900" ; secondColor: "#FF66FF" }
        ListElement { mainColor :"#008800" ; secondColor: "#FF77FF" }
        ListElement { mainColor :"#007700" ; secondColor: "#FF88FF" }
        ListElement { mainColor :"#006600" ; secondColor: "#FF99FF" }
        ListElement { mainColor :"#005500" ; secondColor: "#FFAAFF" }
        ListElement { mainColor :"#004400" ; secondColor: "#FFBBFF" }
        ListElement { mainColor :"#003300" ; secondColor: "#FFCCFF" }
        ListElement { mainColor :"#002200" ; secondColor: "#FFDDFF" }
        ListElement { mainColor :"#001100" ; secondColor: "#FFEEFF" }
        ListElement { mainColor :"#000000" ; secondColor: "#FFFFFF" }
        ListElement { mainColor :"#000011" ; secondColor: "#FFFFEE" }
        ListElement { mainColor :"#000022" ; secondColor: "#FFFFDD" }
        ListElement { mainColor :"#000033" ; secondColor: "#FFFFCC" }
        ListElement { mainColor :"#000044" ; secondColor: "#FFFFBB" }
        ListElement { mainColor :"#000055" ; secondColor: "#FFFFAA" }
        ListElement { mainColor :"#000066" ; secondColor: "#FFFF99" }
        ListElement { mainColor :"#000077" ; secondColor: "#FFFF88" }
        ListElement { mainColor :"#000088" ; secondColor: "#FFFF77" }
        ListElement { mainColor :"#000099" ; secondColor: "#FFFF66" }
        ListElement { mainColor :"#0000AA" ; secondColor: "#FFFF55" }
        ListElement { mainColor :"#0000BB" ; secondColor: "#FFFF44" }
        ListElement { mainColor :"#0000CC" ; secondColor: "#FFFF33" }
        ListElement { mainColor :"#0000DD" ; secondColor: "#FFFF22" }
        ListElement { mainColor :"#0000EE" ; secondColor: "#FFFF11" }
        ListElement { mainColor :"#0000FF" ; secondColor: "#FFFF00" }
    }

    ExpandGridView {
        anchors.fill: parent

        rowSpacing: 1
        colSpacing: 1
        expandSpacing: 1
        fillHeight: false
        fillWidth: false

        cellHeight: 50
        cellWidth: 50
        expandHeight: 256

        expandFillWidth: false
        
        expandDelay: 0
        collapseDelay: 0
        expandDuration: 200
        collapseDuration: 200

        model: objects
        delegate: expandGridViewDelegate
        expandDelegate: expandGridViewExpandDelegate

        ScrollBar.vertical: ScrollBar { }
    }

    Component {
        id: expandGridViewDelegate
        Rectangle {
            color: model ? model.mainColor : "#AA0000"
            width: 50
            height: 50
        }
    }

    Component {
        id: expandGridViewExpandDelegate
        Rectangle {
            width: parent.parent.width
            height: 256
            color: model ? model.secondColor : "#FF0000"
        }
    }
}